[build]
  command = "npm run build:netlify"
  publish = ".next"

[build.environment]
  NETLIFY = "true"
  NODE_VERSION = "20"
  NEXT_PUBLIC_API_URL = "https://backend-project-pemuda.onrender.com/api/v1"
  NEXT_PUBLIC_USE_FALLBACK_DATA = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

# Redirect dashboard paths to login if not authenticated
[[redirects]]
  from = "/dashboard/*"
  to = "/login"
  status = 302
  force = true
