[build]
  command = "npm run build:netlify"
  publish = "out"

[build.environment]
  NETLIFY = "true"
  NODE_VERSION = "20"
  NEXT_PUBLIC_API_URL = "https://backend-project-pemuda.onrender.com/api/v1"

[[plugins]]
  package = "@netlify/plugin-nextjs"
